{
  "id":65,
  "name":"mcuinamespaces",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Namespace",
      "fields":[
        {
          "MIGX_id":1,
          "field":"name",
          "caption":"Name",
          "description":"",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":2,
          "field":"path",
          "caption":"Path",
          "description":"",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        },
        {
          "MIGX_id":3,
          "field":"assets_path",
          "caption":"Assets Path",
          "description":"",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"Add Namespace",
    "formcaption":"Namespace",
    "win_id":"mcuinamespaces",
    "multiple_formtabs":"",
    "extrahandlers":"",
    "packageName":"mycomponentmigxui",
    "classname":"",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":"",
    "joins":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"Name",
      "dataIndex":"name",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":2,
      "header":"Path",
      "dataIndex":"path",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    },
    {
      "MIGX_id":3,
      "header":"Assets Path",
      "dataIndex":"assets_path",
      "width":10,
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2013-03-10 12:09:48",
  "editedby":1,
  "editedon":"2013-03-11 05:12:51",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-03-10 01:00:00",
  "publishedby":0
}