{
  "id":63,
  "name":"mcuidocs",
  "formtabs":[
    {
      "MIGX_id":1,
      "caption":"Doc",
      "fields":[
        {
          "MIGX_id":1,
          "field":"value",
          "caption":"Doc",
          "description":"",
          "inputTV":"",
          "inputTVtype":"",
          "configs":"",
          "sourceFrom":"config",
          "sources":"",
          "inputOptionValues":"",
          "default":""
        }
      ]
    }
  ],
  "contextmenus":"",
  "actionbuttons":"",
  "columnbuttons":"",
  "filters":"",
  "extended":{
    "migx_add":"Add Doc",
    "formcaption":"Doc",
    "win_id":"mcuidocs",
    "multiple_formtabs":"",
    "extrahandlers":"",
    "packageName":"mycomponentmigxui",
    "classname":"",
    "task":"",
    "getlistsort":"",
    "getlistsortdir":"",
    "use_custom_prefix":"0",
    "prefix":"",
    "grid":"",
    "gridload_mode":1,
    "check_resid":1,
    "check_resid_TV":"",
    "join_alias":"",
    "getlistwhere":"",
    "joins":"",
    "cmpmaincaption":"",
    "cmptabcaption":"",
    "cmptabdescription":"",
    "cmptabcontroller":""
  },
  "columns":[
    {
      "MIGX_id":1,
      "header":"Doc",
      "dataIndex":"value",
      "width":"",
      "sortable":"false",
      "show_in_grid":1,
      "renderer":"",
      "clickaction":"",
      "selectorconfig":"",
      "renderoptions":""
    }
  ],
  "createdby":1,
  "createdon":"2013-03-10 09:11:19",
  "editedby":1,
  "editedon":"2013-03-11 05:11:58",
  "deleted":0,
  "deletedon":"-1-11-30 00:00:00",
  "deletedby":0,
  "published":1,
  "publishedon":"2013-03-11 01:00:00",
  "publishedby":0
}